'''

Constants used by DMOS

'''



"""
 Symbols
 """


# 
# Durations
#
SMB_WHOLE_NOTE = "whole"
SMB_HALF_NOTE = "half"
SMB_QUARTER_NOTE = "quarter"
SMB_8TH_NOTE = "quaver"
SMB_16TH_NOTE = "16th"
SMB_32TH_NOTE = "32th"

SMB_WHOLE_REST = "wrest"
SMB_HALF_REST = "hrest"
SMB_QUARTER_REST = "qrest"
SMB_8TH_REST = "8threst"
SMB_16TH_REST = "16threst"
SMB_32TH_REST = "32threst"

NOTE_SYMBOLS_LIST = [SMB_WHOLE_NOTE,SMB_HALF_NOTE,
					SMB_QUARTER_NOTE,SMB_8TH_NOTE,
					 SMB_16TH_NOTE, SMB_32TH_NOTE]
REST_SYMBOLS_LIST = [SMB_WHOLE_REST,SMB_HALF_REST,SMB_QUARTER_REST,
					SMB_8TH_REST, SMB_16TH_REST,SMB_32TH_REST]
DURATION_SYMBOLS_LIST = NOTE_SYMBOLS_LIST + REST_SYMBOLS_LIST

# Clefs

SMB_F_CLEF = "F"
SMB_G_CLEF = "G"
SMB_C_CLEF = "C"

# Headss

SMB_BLACK_HEAD = "blackhead"
SMB_WHITE_HEAD = "whitehead"

SMB_QREST_HEAD = "qresthead"
SMB_HREST_HEAD = "hresthead"
SMB_WREST_HEAD = "wresthead"
SMB_REST_HEAD = "qresthead"
SMB_8THREST_HEAD = "8thresthead"

# Alterations

FLAT_SYMBOL="flat"
SHARP_SYMBOL="sharp"
NATURAL_SYMBOL="natural"
	
# Articulations
ART_STACCATO="staccato"
ART_ACCENT="accent"

ARTICULATIONS_LIST = [ART_STACCATO,ART_ACCENT]

ABOVE="above"
BELOW="below"