'''

Constants used by DMOS

'''

"""
 Symbols
 """


# 
# Durations
#
SMB_WHOLE_NOTE = "whole"
SMB_HALF_NOTE = "half"
SMB_QUARTER_NOTE = "quarter"
SMB_8TH_NOTE = "quaver"
SMB_8TH_NOTE_SYN = "eighth"
SMB_16TH_NOTE = "16th"
SMB_32TH_NOTE = "32th"
SMB_64TH_NOTE = "64th"
SMB_128TH_NOTE = "128th"
SMB_256TH_NOTE = "256th"

SMB_WHOLE_REST = "wrest"
SMB_HALF_REST = "hrest"
SMB_QUARTER_REST = "qrest"
SMB_8TH_REST = "8threst"
SMB_16TH_REST = "16threst"
SMB_32TH_REST = "32threst"
SMB_64TH_REST = "64threst"
SMB_128TH_REST = "128threst"
SMB_256TH_REST = "256threst"

NOTE_SYMBOLS_LIST = [SMB_WHOLE_NOTE,SMB_HALF_NOTE,
					SMB_QUARTER_NOTE,SMB_8TH_NOTE,SMB_8TH_NOTE_SYN,
					 SMB_16TH_NOTE, SMB_32TH_NOTE]
REST_SYMBOLS_LIST = [SMB_WHOLE_REST,SMB_HALF_REST,SMB_QUARTER_REST,
					SMB_8TH_REST, SMB_16TH_REST,SMB_32TH_REST]
DURATION_SYMBOLS_LIST = NOTE_SYMBOLS_LIST + REST_SYMBOLS_LIST

# Clefs
#
# Not used: we rely on Music21 instead
#SMB_F_CLEF = "F"
#SMB_G_CLEF = "G"
#SMB_C_CLEF = "C"

# Heads

SMB_BLACK_HEAD = "blackhead"
SMB_WHITE_HEAD = "whitehead"

SMB_QREST_HEAD = "qresthead"
SMB_HREST_HEAD = "hresthead"
SMB_WREST_HEAD = "wresthead"
SMB_REST_HEAD = "qresthead"
SMB_8THREST_HEAD = "8thresthead"

# Alterations

FLAT_SYMBOL="flat"
DFLAT_SYMBOL="dFlat"
SHARP_SYMBOL="sharp"
DSHARP_SYMBOL="dSharp"
NATURAL_SYMBOL="natural"
	
# Articulations
ART_STACCATO="staccato"
ART_ACCENT="accent"
ART_TENUTO="tenuto"
ART_MARCATO="marcato"
ART_CODA="coda"
ART_SEGNO="segno"
ARTICULATIONS_LIST = [ART_STACCATO,ART_ACCENT,ART_TENUTO,ART_MARCATO,
					  ART_CODA,ART_SEGNO]

# Expression
EXPR_FERMATA="fermata"
EXPR_TRILL="trill"
EXPR_ARPEGGIO="arpeggio"

EXPRESSIONS_LIST = [EXPR_FERMATA,EXPR_TRILL,EXPR_ARPEGGIO]

# Dynamics
DYN_PIANO="p"
DYN_PIANISSIMO="pp"
DYN_FORTE="f"
DYN_FORTISSIMO="ff"
DYN_MEZZOPIANO="mp"
DYN_MEZZOFORTE="mf"

DYNAMICS_LIST = [DYN_PIANO,DYN_PIANISSIMO,DYN_FORTE,DYN_FORTISSIMO,
					  DYN_MEZZOPIANO,DYN_MEZZOFORTE]

ABOVE="above"
BELOW="below"