# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-08 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0003_auto_20180605_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarrule',
            name='creation_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
