# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0005_transcribedopus'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcribedopus',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
