# Generated by Django 2.2.12 on 2020-04-16 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0006_transcribedopus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Corpus'),
        ),
        migrations.AlterField(
            model_name='grammarrule',
            name='grammar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transcription.Grammar'),
        ),
        migrations.AlterField(
            model_name='grammarrule',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transcription.GrammarState'),
        ),
        migrations.AlterField(
            model_name='grammarstate',
            name='grammar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transcription.Grammar'),
        ),
        migrations.AlterField(
            model_name='transcribedopus',
            name='opus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Opus'),
        ),
    ]
