# Generated by Django 2.2.13 on 2021-02-02 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0009_auto_20210201_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='id',
        ),
        migrations.AlterField(
            model_name='grammar',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='ns',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='grammarrule',
            name='grammar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcription.Grammar'),
        ),
    ]
