# Generated by Django 2.2.13 on 2021-02-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0010_auto_20210202_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarrule',
            name='grammar',
        ),
    ]
