# Generated by Django 2.2.13 on 2021-02-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0011_remove_grammarrule_grammar'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammarrule',
            name='grammar',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='transcription.Grammar'),
            preserve_default=False,
        ),
    ]
