# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammar',
            name='parse_failures_ratio',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
