# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0044_auto_20180605_1713'),
        ('transcription', '0004_grammarrule_creation_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscribedOpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Opus')),
            ],
        ),
    ]
