# Generated by Django 2.2.13 on 2021-02-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0007_auto_20200416_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grammar',
            old_name='meter_beat_unit',
            new_name='meter_denominator',
        ),
        migrations.RenameField(
            model_name='grammar',
            old_name='meter_nb_beats',
            new_name='meter_numerator',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='parse_failures_ratio',
        ),
        migrations.AddField(
            model_name='grammar',
            name='initial_state',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grammar',
            name='ns',
            field=models.CharField(max_length=4),
        ),
    ]
