# Generated by Django 2.2.13 on 2021-02-01 17:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0008_auto_20210201_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarrule',
            name='creation_timestamp',
        ),
        migrations.AddField(
            model_name='grammarrule',
            name='occurrences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grammarrule',
            name='symbol',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grammarrule',
            name='type_weight',
            field=models.CharField(choices=[('proba', 'Probabilité')], default='proba', max_length=30),
        ),
        migrations.AlterField(
            model_name='grammarrule',
            name='body',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
        migrations.AlterField(
            model_name='grammarrule',
            name='head',
            field=models.IntegerField(),
        ),
    ]
