# Generated by Django 2.2.13 on 2021-02-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0012_grammarrule_grammar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammar',
            name='creation_timestamp',
        ),
        migrations.RemoveField(
            model_name='grammar',
            name='update_timestamp',
        ),
    ]
