# Generated by Django 2.2.13 on 2021-02-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0013_auto_20210202_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarstate',
            name='grammar',
        ),
    ]
