# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20160616_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simmatrix',
            name='ref',
        ),
    ]
