# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_analyticconcept'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'AnalyticModel',
            },
        ),
        migrations.AddField(
            model_name='analyticconcept',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.AnalyticModel'),
            preserve_default=False,
        ),
    ]
