# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_auto_20170428_1646'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analyticconcept',
            table='AnalyticConcept',
        ),
    ]
