# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_auto_20170502_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticmodel',
            name='code',
            field=models.CharField(default='counterpoint', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
