# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_analyticmodel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticconcept',
            name='code',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
