# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_analyticconcept_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticconcept',
            name='display_options',
            field=models.CharField(default='#ff0000', max_length=255),
        ),
    ]
