# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_analyticconcept_display_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpus',
            options={'permissions': (('view_corpus', 'View corpus'), ('edit_corpus', 'Edit corpus'))},
        ),
    ]
