# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_auto_20170511_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='opus',
            name='external_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
