# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_opus_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opus',
            name='composer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opus',
            name='external_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opus',
            name='lyricist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
