# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import manager.models
import manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_auto_20170512_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='opus',
            name='record',
            field=models.FileField(null=True, storage=manager.utils.OverwriteStorage(), upload_to=manager.models.Opus.upload_path),
        ),
    ]
