# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-13 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0036_annotation_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='ref',
            field=models.TextField(default=''),
        ),
    ]
