# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-11 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0038_auto_20171229_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
