# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import manager.models
import manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0039_auto_20180111_2228'),
    ]

    operations = [
    ]
