# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-29 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0040_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
