# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-25 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0041_annotation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='comment',
            field=models.TextField(default='', null=True),
        ),
    ]
