# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0042_auto_20180425_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticconcept',
            name='icon',
            field=models.CharField(default='', max_length=255),
        ),
    ]
