# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-05 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0043_analyticconcept_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticconcept',
            name='icon',
            field=models.TextField(default=''),
        ),
    ]
