# Generated by Django 2.2.12 on 2020-04-16 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manager.models
import manager.utils
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0045_annotation_xml_fragment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpus',
            options={},
        ),
        migrations.AddField(
            model_name='annotation',
            name='m21_offset',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='analyticconcept',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='analyticconcept',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='analyticconcept',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.AnalyticModel'),
        ),
        migrations.AlterField(
            model_name='analyticconcept',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='manager.AnalyticConcept'),
        ),
        migrations.AlterField(
            model_name='analyticconcept',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='analytic_concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.AnalyticConcept'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='opus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Opus'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kmeans',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.SimMeasure'),
        ),
        migrations.AlterField(
            model_name='opus',
            name='record',
            field=models.FileField(blank=True, null=True, storage=manager.utils.OverwriteStorage(), upload_to=manager.models.Opus.upload_path),
        ),
    ]
