# Generated by Django 2.2.12 on 2020-04-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0046_auto_20200416_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='model_ref',
            field=models.TextField(default=''),
        ),
    ]
