# Generated by Django 2.2.13 on 2020-06-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0047_annotation_model_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptor',
            name='opus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Opus'),
        ),
    ]
