# Generated by Django 3.2.5 on 2021-12-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0052_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='licence_notice',
            field=models.CharField(default='', max_length=255),
        ),
    ]
