# Generated by Django 3.2.5 on 2021-12-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0055_alter_corpus_licence_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opus',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.corpus'),
        ),
    ]
