# Generated by Django 3.2.5 on 2021-12-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0056_alter_opus_corpus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='opus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.opus'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.corpus'),
        ),
    ]
