# Generated by Django 3.2.5 on 2021-12-04 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0057_auto_20211204_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.corpus'),
        ),
    ]
