# Generated by Django 3.2.5 on 2021-12-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0060_alter_licence_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='name',
            field=models.CharField(default='jjj', max_length=100),
            preserve_default=False,
        ),
    ]
