# Generated by Django 3.2.5 on 2021-12-08 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0061_licence_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='copyright',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.licence'),
        ),
    ]
