# Generated by Django 3.2.5 on 2021-12-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0062_auto_20211208_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='supervisors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
