# Generated by Django 3.2.5 on 2021-12-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0063_corpus_supervisors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='licence_notice',
        ),
    ]
