# Generated by Django 2.2.5 on 2021-12-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0064_remove_corpus_licence_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticconcept',
            name='level',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='analyticconcept',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='analyticconcept',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
