# Generated by Django 3.1 on 2022-01-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0064_remove_corpus_licence_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('year_birth', models.IntegerField()),
                ('year_death', models.IntegerField()),
            ],
            options={
                'db_table': 'Person',
            },
        ),
    ]
