# Generated by Django 3.1 on 2022-01-20 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0065_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.person'),
        ),
    ]
