# Generated by Django 2.2.5 on 2022-05-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0066_corpus_composer'),
        ('manager', '0065_auto_20211216_1729'),
    ]

    operations = [
    ]
