# Generated by Django 3.1 on 2022-06-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0067_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='motivation',
            field=models.CharField(choices=[('linking', 'Linking sources'), ('commenting', 'Commenting a target'), ('questioning', 'Questioning a target')], default='linking', max_length=30),
        ),
        migrations.AddField(
            model_name='annotation',
            name='target_class',
            field=models.CharField(choices=[('measure', 'Annotates a measure in a score'), ('note', 'Annotates a note in a score')], default='note', max_length=30),
        ),
    ]
