# Generated by Django 3.1 on 2022-06-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0070_auto_20220601_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='analytic_concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.analyticconcept'),
        ),
    ]
