# Generated by Django 3.1 on 2022-06-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0071_auto_20220601_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticconcept',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.analyticmodel'),
        ),
    ]
