# Generated by Django 3.1 on 2022-06-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0072_auto_20220602_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='target_class',
        ),
    ]
