# Generated by Django 3.1 on 2022-06-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0073_remove_annotation_target_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='textual_body',
            field=models.TextField(null=True),
        ),
    ]
