# Generated by Django 3.1 on 2022-10-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0074_annotation_textual_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opus',
            name='lilypond',
        ),
        migrations.RemoveField(
            model_name='opus',
            name='lilypreview',
        ),
    ]
