# Generated by Django 3.1 on 2022-10-12 13:25

from django.db import migrations, models
import django.db.models.deletion
import manager.models
import manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0075_auto_20221012_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('code', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('mime_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'SourceType',
            },
        ),
        migrations.CreateModel(
            name='OpusSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.TextField()),
                ('description', models.TextField()),
                ('url', models.TextField(null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('source_file', models.FileField(null=True, storage=manager.utils.OverwriteStorage(), upload_to=manager.models.OpusSource.upload_path)),
                ('opus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.opus')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.sourcetype')),
            ],
            options={
                'db_table': 'OpusSource',
            },
        ),
    ]
