# Generated by Django 3.1 on 2022-10-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0076_opussource_sourcetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opussource',
            name='ref',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='opussource',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
