# Generated by Django 3.1 on 2022-10-14 17:40

from django.db import migrations, models
import manager.models
import manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0077_auto_20221012_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='opus',
            name='lilypond',
            field=models.FileField(null=True, storage=manager.utils.OverwriteStorage(), upload_to=manager.models.Opus.upload_path),
        ),
    ]
