# Generated by Django 3.1 on 2022-10-14 17:58

from django.db import migrations, models
import manager.models
import manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0078_opus_lilypond'),
    ]

    operations = [
        migrations.AddField(
            model_name='opus',
            name='dmos_json',
            field=models.FileField(null=True, storage=manager.utils.OverwriteStorage(), upload_to=manager.models.Opus.upload_path),
        ),
        migrations.AddField(
            model_name='opus',
            name='lilypreview',
            field=models.FileField(null=True, storage=manager.utils.OverwriteStorage(), upload_to=manager.models.Opus.upload_path),
        ),
    ]
