# Generated by Django 3.1 on 2022-10-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0079_auto_20221014_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opussource',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
