# Generated by Django 3.1 on 2022-10-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0080_auto_20221019_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opus',
            name='lilypond',
        ),
        migrations.RemoveField(
            model_name='opus',
            name='lilypreview',
        ),
    ]
