# Generated by Django 3.1 on 2022-10-21 15:52

from django.db import migrations, models
import manager.models
import manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0082_auto_20221021_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opus',
            name='mei',
            field=models.FileField(max_length=255, blank=True, null=True, storage=manager.utils.OverwriteStorage(), upload_to=manager.models.Opus.upload_path),
        ),
        migrations.AlterField(
            model_name='opus',
            name='musicxml',
            field=models.FileField(blank=True, null=True, storage=manager.utils.OverwriteStorage(), upload_to=manager.models.Opus.upload_path),
        ),
        migrations.AlterField(
            model_name='opus',
            name='summary',
            field=models.FileField(blank=True, null=True, storage=manager.utils.OverwriteStorage(), upload_to=manager.models.Opus.upload_path),
        ),
    ]
