# Generated by Django 3.1 on 2022-10-25 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0085_auto_20221021_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opussource',
            name='opus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.opus'),
        ),
    ]
