# Generated by Django 3.1 on 2022-11-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0086_auto_20221025_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='fragment',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='m21_offset',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='model_ref',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='xml_fragment',
        ),
        migrations.AlterField(
            model_name='resource',
            name='selector_conforms_to',
            field=models.CharField(choices=[('http://tools.ietf.org/rfc/rfc3023', 'An XPointer expression'), ('https://www.w3.org/TR/media-frags/#naming-space', 'A region in an image'), ('https://www.w3.org/TR/media-frags/#naming-time', 'A segment in an audio or video document')], default='http://tools.ietf.org/rfc/rfc3023', max_length=100),
        ),
    ]
