# Generated by Django 3.1 on 2022-11-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0087_auto_20221126_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='ref',
            field=models.TextField(default=''),
        ),
    ]
