# Generated by Django 3.1 on 2022-11-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0088_annotation_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='selector_conforms_to',
            field=models.CharField(choices=[('http://tools.ietf.org/rfc/rfc3023', 'An XPointer expression'), ('http://www.w3.org/TR/SVG/', 'A region in an image'), ('https://www.w3.org/TR/media-frags/#naming-time', 'A segment in an audio or video document')], default='http://tools.ietf.org/rfc/rfc3023', max_length=100),
        ),
    ]
