# Generated by Django 3.1 on 2022-11-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0089_auto_20221128_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simmatrix',
            name='opus1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_simmatrix_opus1', to='manager.opus'),
        ),
        migrations.AlterField(
            model_name='simmatrix',
            name='opus2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_simmatrix_opus2', to='manager.opus'),
        ),
        migrations.AlterField(
            model_name='simmatrix',
            name='sim_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.simmeasure'),
        ),
    ]
