# Generated by Django 3.1 on 2022-12-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0090_auto_20221128_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dbpedia_uri',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
