# Generated by Django 3.1 on 2022-12-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0091_person_dbpedia_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='analytic_concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.analyticconcept'),
        ),
    ]
