# Generated by Django 2.2.5 on 2023-01-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0092_auto_20221213_1441'),
        ('manager', '0067_merge_20220512_1551'),
    ]

    operations = [
    ]
