# Generated by Django 3.1 on 2023-01-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0093_merge_20230113_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticconcept',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='analyticconcept',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='analyticconcept',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
