# Generated by Django 3.1 on 2023-04-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0094_auto_20230128_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='opus',
            name='composer_ld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.person'),
        ),
    ]
