# Generated by Django 4.2 on 2023-09-14 15:21

from django.db import migrations, models
import manager.models
import manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0096_alter_simmatrix_opus1_alter_simmatrix_opus2"),
    ]

    operations = [
        migrations.AddField(
            model_name="opussource",
            name="manifest",
            field=models.FileField(
                null=True,
                storage=manager.utils.OverwriteStorage(),
                upload_to=manager.models.OpusSource.upload_path,
            ),
        ),
    ]
