# Generated by Django 4.2 on 2023-12-11 18:31

from django.db import migrations, models
import manager.models
import manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0097_opussource_manifest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opussource",
            name="manifest",
            field=models.FileField(
                blank=True,
                null=True,
                storage=manager.utils.OverwriteStorage(),
                upload_to=manager.models.OpusSource.upload_path,
            ),
        ),
    ]
