# Generated by Django 4.2 on 2023-12-14 15:30

from django.db import migrations, models
import django.db.models.deletion
import manager.models
import manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0098_alter_opussource_manifest"),
    ]

    operations = [
    ]
