# Generated by Django 4.2 on 2023-12-14 15:30

from django.db import migrations, models
import django.db.models.deletion
import manager.models
import manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0098_alter_opussource_manifest"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpusDiff",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "musicxml",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=manager.utils.OverwriteStorage(),
                        upload_to=manager.models.OpusDiff.upload_path,
                    ),
                ),
                (
                    "mei",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        storage=manager.utils.OverwriteStorage(),
                        upload_to=manager.models.OpusDiff.upload_path,
                    ),
                ),
                (
                    "opus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="manager.opus"
                    ),
                ),
            ],
        ),
    ]
