# Generated by Django 4.2 on 2023-12-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0099_opusdiff"),
    ]

    operations = [
    ]
