# Generated by Django 4.2 on 2023-12-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0099_opusdiff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="opusdiff", old_name="musicxml", new_name="mei_omr",
        ),
        migrations.RenameField(
            model_name="opusdiff", old_name="mei", new_name="mei_ref",
        ),
    ]
