# Generated by Django 4.2 on 2024-02-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0100_rename_musicxml_opusdiff_mei_omr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opussource",
            name="operations",
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
