# Generated by Django 4.2 on 2024-02-06 11:03

from django.db import migrations, models
import manager.models
import manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0101_opussource_operations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opussource",
            name="source_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=manager.utils.OverwriteStorage(),
                upload_to=manager.models.OpusSource.upload_path,
            ),
        ),
    ]
