# Generated by Django 4.2 on 2024-10-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0103_annotation_web_annotation"),
    ]

    operations = [
        migrations.RemoveField(model_name="patterns", name="opus",),
        migrations.RemoveField(model_name="simmatrix", name="opus1",),
        migrations.RemoveField(model_name="simmatrix", name="opus2",),
        migrations.RemoveField(model_name="simmatrix", name="sim_measure",),
        migrations.AlterField(
            model_name="opussource",
            name="operations",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(name="Kmeans",),
        migrations.DeleteModel(name="Patterns",),
        migrations.DeleteModel(name="SimMatrix",),
        migrations.DeleteModel(name="SimMeasure",),
    ]
