# Generated by Django 4.2 on 2024-10-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0104_remove_patterns_opus_remove_simmatrix_opus1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opussource",
            name="operations",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
