# Generated by Django 4.2 on 2025-01-02 16:49

from django.db import migrations, models
import manager.models
import manager.utils


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0106_opussource_iiif_manifest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opussource",
            name="iiif_manifest",
            field=models.FileField(
                blank=True,
                null=True,
                storage=manager.utils.OverwriteStorage(),
                upload_to=manager.models.OpusSource.upload_path,
            ),
        ),
    ]
