# Generated by Django 5.2 on 2025-07-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0107_alter_opussource_iiif_manifest"),
    ]

    operations = [
        migrations.AddField(
            model_name="opussource",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
