# Generated by Django 5.2 on 2025-10-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0108_opussource_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="opussource",
            name="is_iiif",
            field=models.BooleanField(default=False),
        ),
    ]
