# Generated by Django 5.2 on 2025-10-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0109_opussource_is_iiif"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "code",
                    models.CharField(
                        default="default",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("log_level", models.CharField(default=30, max_length=80)),
                ("page_min", models.IntegerField(default=0)),
                ("page_max", models.IntegerField(default=9223372036854775807)),
                ("system_min", models.IntegerField(default=0)),
                ("system_max", models.IntegerField(default=9223372036854775807)),
                ("measure_min", models.IntegerField(default=0)),
                ("measure_max", models.IntegerField(default=9223372036854775807)),
                ("ensure_measure_duration", models.BooleanField(default=True)),
            ],
            options={"db_table": "Config",},
        ),
    ]
