# Generated by Django 5.2 on 2025-10-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0110_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="measure_max",
            field=models.IntegerField(default=32767),
        ),
        migrations.AlterField(
            model_name="config",
            name="page_max",
            field=models.IntegerField(default=32767),
        ),
        migrations.AlterField(
            model_name="config",
            name="system_max",
            field=models.IntegerField(default=32767),
        ),
    ]
