# Generated by Django 5.2 on 2025-10-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0111_alter_config_measure_max_alter_config_page_max_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="log_level",
            field=models.IntegerField(default=30),
        ),
    ]
