# Generated by Django 5.2 on 2025-10-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0112_alter_config_log_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="enable_score_caching",
            field=models.BooleanField(default=True),
        ),
    ]
