# Generated by Django 5.2 on 2025-11-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0113_config_enable_score_caching"),
    ]

    operations = [
        migrations.AddField(
            model_name="opus",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
