# Generated by Django 5.2 on 2025-11-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0114_opus_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iiif_url",
                    models.URLField(
                        max_length=512, unique=True, verbose_name="IIIF URL"
                    ),
                ),
                ("width", models.PositiveIntegerField(default=0, verbose_name="Width")),
                (
                    "height",
                    models.PositiveIntegerField(default=0, verbose_name="Height"),
                ),
            ],
            options={"verbose_name": "Image", "verbose_name_plural": "Images",},
        ),
        migrations.AddField(
            model_name="corpus",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corpuses",
                to="manager.image",
                verbose_name="Image",
            ),
        ),
    ]
