# Generated by Django 5.2 on 2025-11-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0115_image_corpus_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="iiif_id",
            field=models.CharField(
                default="kl", max_length=30, unique=True, verbose_name="IIIF ID"
            ),
            preserve_default=False,
        ),
    ]
