# Generated by Django 5.2 on 2025-11-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0116_image_iiif_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpus",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corpuses",
                to="manager.image",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("homepage", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizations",
                        to="manager.image",
                        verbose_name="Logo",
                    ),
                ),
            ],
            options={"db_table": "Organization",},
        ),
    ]
