# Generated by Django 5.2 on 2025-11-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0117_alter_corpus_thumbnail_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="corpus",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manager.organization",
            ),
        ),
    ]
