# Generated by Django 5.2 on 2025-12-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0118_corpus_organization"),
    ]

    operations = [
        migrations.RemoveField(model_name="opus", name="composer",),
    ]
