# Generated by Django 5.2 on 2025-12-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0119_remove_opus_composer_remove_opusdiff_mei_omr_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="opus", old_name="composer_ld", new_name="composer",
        ),
    ]
