# Generated by Django 5.2 on 2025-12-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0120_rename_composer_ld_opus_composer"),
    ]

    operations = [
        migrations.AddField(
            model_name="opus",
            name="features",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="opus",
            name="metadata",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
