# Generated by Django 5.2 on 2025-12-01 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0121_opus_features_opus_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="opussource",
            name="copyright",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opussource",
            name="licence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="manager.licence",
            ),
        ),
        migrations.AddField(
            model_name="opussource",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="manager.organization",
            ),
        ),
        migrations.AddField(
            model_name="opussource",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sources",
                to="manager.image",
                verbose_name="Thumbnail",
            ),
        ),
    ]
