# Generated by Django 5.2 on 2025-12-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0122_opussource_copyright_opussource_licence_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="OpusMeta",),
    ]
