# Generated by Django 5.2 on 2025-12-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0123_delete_opusmeta"),
    ]

    operations = [
        migrations.RemoveField(model_name="opus", name="external_link",),
        migrations.RemoveField(model_name="opus", name="lyricist",),
    ]
