# Generated by Django 5.2 on 2025-12-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0124_remove_opus_external_link_remove_opus_lyricist"),
    ]

    operations = [
        migrations.AddField(
            model_name="opus",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
